[cursor.style]
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 1

[window]
opacity = 0.8

[window.padding]
x = 0
y = 0

[general]
import = ["/home/noname/.config/alacritty/bloop.toml"]
