local colors = require("colors")

local theme = {
	-- UI: Base and Editor
	Normal                      = { fg = colors.fg, bg = colors.bg },
	Bold                        = { bold = true },
	Italic                      = { italic = false },
	Underlined                  = { underline = true },
	ColorColumn                 = { bg = colors.lightbg },
	Cursor                      = { fg = colors.bg, bg = "#39051A" },
	CursorColumn                = { bg = "#262D36" },
	CursorIM                    = {},
	CursorLine                  = { bg = "#262D36" },
	CursorLineNr                = { fg = colors.red },
	LineNr                      = { fg = colors.purple_alt },
	VertSplit                   = { fg = "#262D36" },
	SignColumn                  = { fg = colors.dark_purple },
	Visual                      = { bg = colors.lightbg },
	VisualNOS                   = { bg = "#262D36" },
	NonText                     = { fg = colors.lightbg },
	Whitespace                  = { link = "NonText" },
	EndOfBuffer                 = { fg = colors.purple_alt },
	Conceal                     = { fg = colors.dark_green },

	-- UI: Navigation and Menus
	StatusLine                  = { fg = colors.dark_purple },
	StatusLineNC                = { fg = colors.purple_alt },
	TabLine                     = { fg = colors.dark_purple },
	TabLineFill                 = { link = "TabLine" },
	TabLineSel                  = { fg = colors.green, bg = "#262D36" },
	Pmenu                       = { fg = colors.fg, bg = colors.black },
	PmenuSel                    = { fg = colors.fg, bg = colors.lightbg },
	PmenuSbar                   = { fg = colors.green, bg = colors.black2 },
	PmenuThumb                  = { bg = colors.lightbg },
	WildMenu                    = { fg = colors.fg, bg = colors.lightbg },
	Directory                   = { fg = colors.green },
	QuickFixLine                = { fg = colors.green },
	Folded                      = { fg = colors.dark_purple, bg = colors.lightbg },
	FoldColumn                  = { link = "Folded" },

	-- Search and Messages
	Search                      = { bg = "#39051A" },
	IncSearch                   = { fg = colors.red, bg = colors.lightbg },
	Substitute                  = { fg = colors.red, bg = "#39051A" },
	MatchParen                  = { fg = colors.red, bg = colors.lightbg },
	Question                    = { fg = colors.orange },
	ModeMsg                     = { fg = colors.purple_alt },
	MoreMsg                     = { fg = colors.green },
	MsgArea                     = { fg = colors.dark_purple },
	MsgSeparator                = { fg = colors.purple_alt },
	ErrorMsg                    = { fg = colors.red, bg = "#39051A" },
	WarningMsg                  = { fg = colors.red },
	WarnMsg                     = { fg = colors.dark_purple, bg = "#0B0C0F", bold = true },
	InfoMsg                     = { fg = colors.dark_purple },
	HintMsg                     = { fg = colors.green },

	-- Syntax: Standard Base
	Comment                     = { fg = colors.dark_purple },
	SpecialComment              = { fg = colors.cyan },
	Constant                    = { fg = colors.green },
	Boolean                     = { link = "Constant" },
	Character                   = { link = "Constant" },
	Float                       = { link = "Constant" },
	Number                      = { link = "Constant" },
	String                      = { link = "Constant" },
	Identifier                  = { fg = colors.red },
	Function                    = { fg = colors.cyan },
	Keyword                     = { fg = colors.red },
	Statement                   = { link = "Keyword" },
	Conditional                 = { link = "Statement" },
	Repeat                      = { link = "Statement" },
	Label                       = { link = "Statement" },
	Operator                    = { link = "Statement" },
	PreProc                     = { fg = colors.purple },
	Include                     = { link = "Keyword" },
	Type                        = { fg = colors.orange },
	Typedef                     = { fg = colors.orange },
	Special                     = { fg = colors.red },
	Tag                         = { fg = colors.orange },
	Delimiter                   = { link = "Noise" },
	Debug                       = { fg = colors.orange, bg = colors.lightbg },
	Ignore                      = {},
	Error                       = { link = "ErrorMsg" },
	NvimInternalError           = { link = "ErrorMsg" },

	-- Syntax: Noise and Punctuation
	Noise                       = { fg = colors.purple_alt },
	Assign                      = { link = "Noise" },
	Braces                      = { link = "Noise" },
	Comma                       = { link = "Noise" },
	Parens                      = { link = "Noise" },

	-- Tree-sitter 
	["@variable"]               = { fg = colors.fg },
	["@variable.builtin"]       = { fg = colors.green },
	["@variable.member"]        = { fg = colors.purple },
	["@variable.member.lua"]    = { link = "Identifier" },
	["@property"]               = { fg = colors.purple },
	["@constructor"]            = { fg = colors.red },
	["@module"]                 = { fg = colors.purple },
	["@function.method"]        = { fg = colors.cyan },
	["@keyword"]                = { link = "Keyword" },
	["@keyword.function"]       = { link = "Keyword" },
	["@keyword.operator"]       = { fg = colors.red },
	["@keyword.return"]         = { fg = colors.red, bold = true },
	["@operator"]               = { link = "Noise" },
	["@punctuation.bracket"]    = { link = "Noise" },
	["@punctuation.delimiter"]  = { link = "Noise" },
	["@tag"]                    = { fg = colors.dark_purple },
	["@tag.attribute"]          = { fg = colors.dark_purple },
	["@tag.delimiter"]          = { link = "Noise" },
	["@comment.note"]           = { fg = colors.green },
	["@comment.warning"]        = { fg = colors.red },
	["@error"]                  = { link = "Error" },

	-- Legacy Tree-sitter
	TSVariable                  = { fg = colors.fg },
	TSVariableBuiltin           = { fg = colors.green },
	TSField                     = { fg = colors.purple },
	TSProperty                  = { fg = colors.purple },
	TSConstructor               = { fg = colors.orange },
	TSNamespace                 = { fg = colors.purple },
	TSMethod                    = { fg = colors.cyan },
	TSKeyword                   = { link = "Keyword" },
	TSKeywordFunction           = { link = "Keyword" },
	TSKeywordOperator           = { fg = colors.red },
	TSKeywordReturn             = { fg = colors.red, bold = true },
	TSOperator                  = { link = "Noise" },
	TSPunctBracket              = { link = "Noise" },
	TSPunctDelimiter            = { link = "Noise" },
	TSTag                       = { fg = colors.dark_purple },
	TSTagAttribute              = { fg = colors.dark_purple },
	TSTagDelimiter              = { link = "Noise" },
	TSNote                      = { fg = colors.green },
	TSWarning                   = { fg = colors.red },
	TSDanger                    = { link = "Error" },
	luaTSConstructor            = { link = "Noise" },

	-- Diagnostics
	DiagnosticError             = { link = "ErrorMsg" },
	DiagnosticWarn              = { link = "WarnMsg" },
	DiagnosticInfo              = { link = "InfoMsg" },
	DiagnosticHint              = { link = "HintMsg" },
	DiagnosticSignError         = { fg = colors.red },
	DiagnosticSignWarn          = { fg = colors.cyan },
	DiagnosticSignInfo          = { fg = colors.purple },
	DiagnosticSignHint          = { fg = colors.purple_alt },
	DiagnosticUnderlineError    = {},
	DiagnosticUnderlineWarn     = {},
	DiagnosticUnderlineInfo     = {},
	DiagnosticUnderlineHint     = {},

	-- LSP and Floating Windows
	NormalFloat                 = { fg = colors.fg, bg = colors.bg2 },
	FloatNormal                 = { link = "NormalFloat" },
	FloatBorder                 = { fg = colors.lightbg, bg = colors.bg },
	LspFloatWinBorder           = { link = "FloatBorder" },
	LspFloatWinNormal           = { link = "FloatNormal" },
	LspReferenceRead            = { bg = colors.lightbg },
	LspReferenceText            = { bg = colors.lightbg },
	LspReferenceWrite           = { bg = colors.lightbg },
	LspSignatureActiveParameter = { link = "LspReferenceText" },

	-- Git and Diffs
	DiffAdd                     = { fg = colors.green },
	DiffChange                  = { fg = colors.dark_green },
	DiffDelete                  = { fg = colors.red },
	DiffText                    = { bg = "#262D36" },
	GitSignsAdd                 = { fg = colors.green },
	GitSignsChange              = { fg = colors.dark_green },
	GitSignsDelete              = { fg = colors.red },
	GitGutterAdd                = { link = "GitSignsAdd" },
	GitGutterChange             = { link = "GitSignsChange" },
	GitGutterDelete             = { link = "GitSignsDelete" },

	-- External Plugins
	TelescopeBorder             = { link = "FloatBorder" },
	TelescopeNormal             = { link = "FloatNormal" },
	TelescopeTitle              = { fg = colors.red },
	WhichKey                    = { fg = colors.green },
	WhichKeyFloat               = { link = "FloatNormal" },
	NvimTreeNormal              = { link = "FloatNormal" },
	NeoTreeTitleBar             = { fg = colors.fg, bg = colors.black2 },
	NeoTreeNormal               = { link = "FloatNormal" },
	NeoTreeNormalNC             = { link = "FloatNormal" },
	NeoTreeFloatBorder          = { fg = colors.black2, bg = colors.black2 },

	-- Terminal
	TermNormal                  = { bg = "#0B0C0F" },
	TermCursor                  = { reverse = true },
	TermCursorNC                = { bg = "#262D36" },
	Title                       = { fg = colors.fg },

	-- Markdown
	markdownH1                  = { fg = colors.red, bold = true },
	markdownH2                  = { fg = colors.green },
	markdownH3                  = { fg = colors.green },
	markdownH4                  = { fg = colors.dark_purple },
	markdownH5                  = { fg = colors.dark_purple },
	markdownH6                  = { fg = colors.dark_purple },
}
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='bloop'")

for group, attributes in pairs(theme) do
	vim.api.nvim_set_hl(0, group, attributes)
end
