#!/bin/bash
xsetroot -cursor_name left_ptr
! pgrep -X picom && picom &

pkill sxhkd
sxhkd &
feh --bg-scale ~/.config/bspwm/wallpaper &

bspc monitor -d I II III IV

# window borders
bspc config window_gap 12
bspc config border_width 2
bspc config focused_border_color '#545277'
bspc config normal_border_color '#282838'

# windo gaps
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a Emacs state=tiled

# eww
bspc rule -a Eww manage=off state=floating
bspc config left_padding 45

eww open bar_1
sleep 1
stalonetray &
