(deftheme bloop-nvim-light
  "Bloop dark theme I use for text editing")

(mapcar #'disable-theme custom-enabled-themes)

(let* ((bg2         "#ededfc")
       (bg          "#f7f4fb")
       (black2      "#f0effb")
       (black       "#f5f4ff")
       (fg          "#2a2a3e")
       (lightbg2    "#dddaf5")
       (lightbg     "#d0cce8")

       (dark_green  "#1a7a40")
       (wine        "#e8d0f0")
       (blue        "#1a7ab5")
       (cyan        "#1070a8")
       (green       "#2a8c4a")
       (purple_alt  "#8a85c2")
       (dark_purple "#8085b0")
       (purple      "#5048a0")
       (red         "#c52a4e")
       (yellow      "#5a5000")
       (orange      "#c07060")
       (white       "#1a1030"))
  (custom-theme-set-faces
   'bloop-nvim-light
   ;; Editor core
   `(default                             ((t :background ,bg :foreground ,fg)))
   `(cursor                              ((t :background ,lightbg :foreground ,bg)))
   `(fringe                              ((t :background ,bg :foreground ,purple_alt)))
   `(region                              ((t :background ,lightbg :foreground ,fg)))
   `(highlight                           ((t :background ,lightbg2)))
   `(shadow                              ((t :foreground ,purple_alt)))
   `(link                                ((t :foreground ,blue :underline t)))
   `(link-visited                        ((t :foreground ,purple :underline t)))
   `(match                               ((t :background ,lightbg :foreground ,red :weight bold)))
   `(lazy-highlight                      ((t :background ,lightbg2 :foreground ,fg)))
   `(trailing-whitespace                 ((t :foreground ,wine)))
   `(escape-glyph                        ((t :foreground ,yellow)))
   `(error                               ((t :foreground ,red :weight bold)))
   `(warning                             ((t :foreground ,orange)))
   `(success                             ((t :foreground ,green)))
   `(line-number                         ((t :background ,bg :foreground ,purple_alt)))
   `(line-number-current-line            ((t :background ,bg :foreground ,red)))
   `(vertical-border                     ((t :foreground ,lightbg)))
   `(minibuffer-prompt                   ((t :background ,bg :foreground ,purple :weight bold)))

   ;; modeline
   `(mode-line                            ((t :background ,wine :foreground ,fg)))
   `(mode-line-inactive                   ((t :background ,bg :foreground ,dark_purple)))
   `(mode-line-active                     ((t :background ,wine :foreground ,fg)))
   `(mode-line-highlight                  ((t :foreground ,red)))
   `(mode-line-buffer-id                  ((t :foreground ,red :weight bold)))

   ;; syntax
   `(font-lock-keyword-face              ((t :foreground ,red :weight bold)))
   `(font-lock-string-face               ((t :foreground ,green)))
   `(font-lock-comment-face              ((t :foreground ,dark_purple)))
   `(font-lock-function-name-face        ((t :foreground ,cyan)))
   `(font-lock-type-face                 ((t :foreground ,orange)))
   `(font-lock-variable-name-face        ((t :foreground ,fg)))
   `(font-lock-constant-face             ((t :foreground ,fg)))
   `(font-lock-warning-face              ((t :foreground ,red)))
   `(font-lock-builtin-face              ((t :foreground ,red :weight bold)))
   `(font-lock-preprocessor-face         ((t :foreground ,purple :weight bold)))
   `(font-lock-number-face               ((t :foreground ,green)))

   ;; rainbow delimiters
   `(rainbow-delimiters-depth-1-face     ((t :foreground ,purple_alt)))
   `(rainbow-delimiters-depth-2-face     ((t :foreground ,purple_alt)))
   `(rainbow-delimiters-depth-3-face     ((t :foreground ,purple_alt)))
   `(rainbow-delimiters-depth-4-face     ((t :foreground ,purple_alt)))
   `(rainbow-delimiters-depth-5-face     ((t :foreground ,purple_alt)))
   `(rainbow-delimiters-depth-6-face     ((t :foreground ,purple_alt)))
   `(rainbow-delimiters-depth-7-face     ((t :foreground ,purple_alt)))
   `(rainbow-delimiters-depth-8-face     ((t :foreground ,purple_alt)))
   `(rainbow-delimiters-depth-9-face     ((t :foreground ,purple_alt)))
   
   ;; Treesitter syntax
   `(treesit-font-lock-property-use-face ((t :foreground ,red)))
   `(treesit-font-lock-comment-face      ((t :foreground ,dark_purple)))
   `(treesit-font-lock-constant-face     ((t :foreground ,green)))
   `(treesit-font-lock-constructor-face  ((t :foreground ,red)))
   `(treesit-font-lock-doc-face          ((t :foreground ,dark_purple)))
   `(treesit-font-lock-escape-face       ((t :foreground ,red)))
   `(treesit-font-lock-function-face     ((t :foreground ,cyan)))
   `(treesit-font-lock-keyword-face      ((t :foreground ,red)))
   `(treesit-font-lock-label-face        ((t :foreground ,red)))
   `(treesit-font-lock-number-face       ((t :foreground ,green)))
   `(treesit-font-lock-operator-face     ((t :foreground ,purple_alt)))
   `(treesit-font-lock-bracket-face      ((t :foreground ,purple_alt)))
   `(treesit-font-lock-property-face     ((t :foreground ,purple)))
   `(treesit-font-lock-punctuation-face  ((t :foreground ,purple_alt)))
   `(treesit-font-lock-string-face       ((t :foreground ,green)))
   `(treesit-font-lock-type-face         ((t :foreground ,orange)))
   `(treesit-font-lock-variable-face     ((t :foreground ,fg)))

   `(font-lock-comment-face              ((t :foreground ,dark_purple)))
   `(font-lock-constant-face             ((t :foreground ,green)))
   `(font-lock-constructor-face          ((t :foreground ,red)))
   `(font-lock-doc-face                  ((t :foreground ,dark_purple)))
   `(font-lock-escape-face               ((t :foreground ,red)))
   `(font-lock-property-use-face         ((t :foreground ,red)))
   `(font-lock-function-face             ((t :foreground ,cyan)))
   `(font-lock-keyword-face              ((t :foreground ,red)))
   `(font-lock-label-face                ((t :foreground ,red)))
   `(font-lock-number-face               ((t :foreground ,green)))
   `(font-lock-operator-face             ((t :foreground ,purple_alt)))
   `(font-lock-bracket-face              ((t :foreground ,purple_alt)))
   `(font-lock-property-face             ((t :foreground ,purple)))
   `(font-lock-punctuation-face          ((t :foreground ,purple_alt)))
   `(font-lock-string-face               ((t :foreground ,green)))
   `(font-lock-type-face                 ((t :foreground ,orange)))
   `(font-lock-variable-face             ((t :foreground ,fg)))))
